spring.application.name=Banking_management_system
spring.datasource.url=jdbc:mysql://localhost:3306/Banking_management_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
